builder.CreateFile("xlsx");
var oWorksheet = Api.GetActiveSheet();
var oSheet = Api.AddSheet("New sheet");
oWorksheet = Api.GetSheet("New sheet");
Api.SetLocale("en-CA");
oWorksheet.GetRange("A1").SetValue("Locale: ");
oWorksheet.GetRange("B1").SetValue(Api.GetLocale());
Api.AddDefName("locale", "Sheet1!$A$1:$B$1");
var oFill = Api.CreateSolidFill(Api.CreateRGBColor(104, 155, 104));
var oStroke = Api.CreateStroke(0, Api.CreateNoFill());
var oShape = oWorksheet.AddShape("flowChartOnlineStorage", 120 * 36000, 35 * 36000, oFill, oStroke, 0, 5 * 36000, 0, 10 * 36000);
oDocContent = oShape.GetDocContent();
oParagraph = oDocContent.GetElement(0);
oParagraph.AddText(" This is an example for base class methods.");
oBullet = Api.CreateNumbering("ArabicParenR", 1);
oParagraph = Api.CreateParagraph();
oParagraph.SetBullet(oBullet);
oParagraph.AddText(" A sheet named 'New sheet' was added.");
oDocContent.Push(oParagraph);
oParagraph = Api.CreateParagraph();
oParagraph.SetBullet(oBullet);
oParagraph.AddText(" The language of the document was set to English (Canada).");
oDocContent.Push(oParagraph);
oParagraph = Api.CreateParagraph();
oParagraph.SetBullet(oBullet);
oParagraph.AddText(" A green shape was created with numbered paragraphs in it.");
oDocContent.Push(oParagraph);
builder.SaveFile("xlsx", "Api.xlsx");
builder.CloseFile();