builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var oRun = Api.CreateRun();
oRun.AddText("Add a combo box to the next line (Forms -> Combo Box), copy the macro above (without the first and last two lines) and run it (Plugins -> Macros).");
oParagraph.AddElement(oRun);
var aForms = oDocument.GetAllForms();
oParagraph.RemoveElement(0);
aForms[0].SetBorderColor(255, 0, 0);
aForms[0].SetFixedForm(true);
aForms[0].SetText("Country");
var sText = aForms[0].GetText();
var sClassType = aForms[0].GetClassType();
var sFormType = aForms[0].GetFormType();
var bFixed = aForms[0].IsFixedForm();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Class type: " + sClassType);
oParagraph.AddLineBreak();
oParagraph.AddText("Form type: " + sFormType);
oParagraph.AddLineBreak();
oParagraph.AddText("Form text: " + sText);
oParagraph.AddLineBreak();
oParagraph.AddText("The first form from this document is fixed: " + bFixed);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "ApiFormBase.docx");
builder.CloseFile();