builder.CreateFile("docx");
var Document = Api.GetDocument();
var Paragraph = Document.GetElement(0);
var InlineLvlSdt = Api.CreateInlineLvlSdt();
Paragraph.AddInlineLvlSdt(InlineLvlSdt);
var Run = Api.CreateRun();
Run.AddText("This is an inline text content control.");
InlineLvlSdt.AddElement(Run, 0);
builder.SaveFile("docx", "CreateInlineLvlSdt.docx");
builder.CloseFile();