builder.CreateFile("docx");
var Document = Api.GetDocument();
var Paragraph = Document.GetElement(0);
Paragraph.AddText('This is just a sample text.');
Document.CreateNewHistoryPoint();
Paragraph = Api.CreateParagraph();
Paragraph.AddText('New history point was just created.');
Document.Push(Paragraph);
builder.SaveFile("docx", "CreateNewHistoryPoint.docx");
builder.CloseFile();