builder.CreateFile("docx");
oDocument = Api.GetDocument();
oTableStyle = oDocument.CreateStyle("CustomTableStyle", "table");
oTableStyle.SetBasedOn(oDocument.GetStyle("Bordered - Accent 5"));
oTable = Api.CreateTable(3, 3);
oTable.SetWidth("percent", 100);
oTable.SetStyle(oTableStyle);
oDocument.Push(oTable);
oTable.GetCell(0, 0).GetContent().GetElement(0).AddText("Cell 1");
oParentTable = oTable.GetCell(0, 0).GetParentTable();
oParentTable.SetTableBorderTop("single", 32, 0, 0, 0, 255);
builder.SaveFile("docx", "GetParentTable.docx");
builder.CloseFile();