builder.CreateFile("docx");
var Document = Api.GetDocument();
var Paragraph, Stroke, Fill, DocContent;
Paragraph = Document.GetElement(0);
Fill = Api.CreateSolidFill(Api.CreateRGBColor(104, 155, 104));
Stroke = Api.CreateStroke(0, Api.CreateNoFill());
Drawing = Api.CreateShape("rect", 3212465, 963295, Fill, Stroke);
Paragraph.AddDrawing(Drawing);
DocContent = Drawing.GetDocContent();
Paragraph = Api.CreateParagraph();
Paragraph.AddText("This is a sample text with paddings set to it: left = 5 * 36000, top = 1 * 36000, right = 10 * 36000, bottom = 2 * 36000.");
DocContent.Push(Paragraph);
Drawing.SetPaddings(5 * 36000, 1 * 36000, 10 * 36000, 2 * 36000);
builder.SaveFile("docx", "SetPaddings.docx");
builder.CloseFile();