builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var oRun = Api.CreateRun();
oRun.AddText("Add a radio button to the next line (Forms -> Radio Button), copy the macro above (without the first and last two lines) and run it (Plugins -> Macros).");
oParagraph.AddElement(oRun);
var aRadioButton = oDocument.GetAllForms();
oParagraph.RemoveElement(0);
aRadioButton[0].SetRadioGroup("Radio Group 1");
var sRadioGroup = aRadioButton[0].GetRadioGroup();
var bRadioButton = aRadioButton[0].IsRadioButton();
aRadioButton[0].SetChecked(true);
var bChecked = aRadioButton[0].IsChecked();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("The first content control from this document is a radio button: " + bRadioButton);
oParagraph.AddLineBreak();
oParagraph.AddText("The first radio button from this document is checked: " + bChecked);
oParagraph.AddLineBreak();
oParagraph.AddText("Radio group name of the first radio button in this document: " + sRadioGroup);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "ApiCheckBoxForm.docx");
builder.CloseFile();