builder.CreateFile("pptx");
var Presentation = Api.GetPresentation();
var Table = Api.CreateTable(2, 4);
var Row = Table.GetRow(0);
var Cell = Row.GetCell(0);
var Content = Cell.GetContent();
var Paragraph = Api.CreateParagraph();
Paragraph.AddText("This is just a sample text.");
Content.Push(Paragraph);
Cell.SetCellMarginBottom(600);
var Slide = Presentation.GetSlideByIndex(0);
Slide.RemoveAllObjects();
Slide.AddObject(Table);
builder.SaveFile("pptx", "SetCellMarginBottom.pptx");
builder.CloseFile();