builder.CreateFile("pptx");
var Presentation = Api.GetPresentation();
var Table = Api.CreateTable(2, 4);
var Row = Table.GetRow(0);
Row.SetHeight(30 * 36000);
var Cell = Row.GetCell(0);
Cell.SetTextDirection("tbrl");
var Content = Cell.GetContent();
var Paragraph = Api.CreateParagraph();
Paragraph.AddText("This is just a sample text.");
Content.Push(Paragraph);
var Slide = Presentation.GetSlideByIndex(0);
Slide.RemoveAllObjects();
Slide.AddObject(Table);
builder.SaveFile("pptx", "SetTextDirection.pptx");
builder.CloseFile();