builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oMaster = oPresentation.GetMaster();
oFill = Api.CreateSolidFill(Api.CreateRGBColor(104, 155, 104));
oMaster.SetBackground(oFill);
oLayout = Api.CreateLayout(oMaster);
oLayout.FollowMasterBackground();
builder.SaveFile("pptx", "FollowMasterBackground.pptx");
builder.CloseFile();