builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oMaster = oPresentation.GetMaster(0);
oFill = Api.CreateSolidFill(Api.CreateRGBColor(104, 155, 104));
oMaster.SetBackground(oFill);
oLayout = oMaster.GetLayout(0);
oLayout.FollowMasterBackground();
oSlide.FollowLayoutBackground();
builder.SaveFile("pptx", "FollowMasterBackground.pptx");
builder.CloseFile();