builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oMaster = oPresentation.GetMaster();
oLayout = Api.CreateLayout(oMaster);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 224, 204), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 164, 101), 100000);
oFill = Api.CreateLinearGradientFill([oGs1, oGs2], 5400000);
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oShape1 = Api.CreateShape("rect", 3212465, 963295, oFill, oStroke);
oLayout.AddDrawing(oShape1);
oShape2 = Api.CreateShape("wave", 3212465, 963295, oFill, oStroke);
oLayout.AddDrawing(oShape2);
aShapes = oLayout.GetAllShapes();
oFill = Api.CreateSolidFill(Api.CreateRGBColor(61, 74, 107));
aShapes[0].Fill(oFill);
builder.SaveFile("pptx", "GetAllShapes.pptx");
builder.CloseFile();