builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide1 = oPresentation.GetSlideByIndex(0);
oMaster = oPresentation.GetMaster(0);
oLayout1 = oMaster.GetLayout(3);
oSlide1.ApplyLayout(oLayout1);
oLayout1.MoveTo(7);
oLayout2 = oMaster.GetLayout(3);
oSlide2 = Api.CreateSlide();
oPresentation.AddSlide(oSlide2);
oSlide2.ApplyLayout(oLayout2);
oLayout3 = oMaster.GetLayout(7);
oSlide3 = Api.CreateSlide();
oPresentation.AddSlide(oSlide3);
oSlide3.ApplyLayout(oLayout3);
builder.SaveFile("pptx", "MoveTo.pptx");
builder.CloseFile();