builder.CreateFile("docx");
oDocument = Api.GetDocument();
oParagraph1 = oDocument.GetElement(0);
oParagraph1.AddText("Heading 1");
oHeading1Style = oDocument.GetStyle("Heading 1");
oParagraph1.SetStyle(oHeading1Style);
oParagraph2 = Api.CreateParagraph();
oParagraph2.AddText("This document will be converted to Markdown.");
oDocument.Push(oParagraph2);
oParagraph3 = Api.CreateParagraph();
oParagraph3.AddText("Heading 2");
oDocument.Push(oParagraph3);
oHeading2Style = oDocument.GetStyle("Heading 2");
oParagraph3.SetStyle(oHeading2Style);
oParagraph4 = Api.CreateParagraph();
oParagraph4.AddText("There is an example of two heading levels.");
oDocument.Push(oParagraph4);
sMarkdown = Api.ConvertDocument("markdown", false, false, true, false);
oParagraph5 = Api.CreateParagraph();
oParagraph5.AddText(sMarkdown);
oDocument.Push(oParagraph5);
builder.SaveFile("docx", "ConvertDocument.docx");
builder.CloseFile();