builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var oRun = Api.CreateRun();
oRun.AddText("Add a text form to the next line (Forms -> Text Field), copy the macro above (without the first and last two lines) and run it (Plugins -> Macros).");
oParagraph.AddElement(oRun);
var aTextForm = oDocument.GetAllForms();
oParagraph.RemoveElement(0);
aTextForm[0].SetComb(true);
var bComb = aTextForm[0].IsComb();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("The first text form from this document is comb: " + bComb);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "IsComb.docx");
builder.CloseFile();