builder.CreateFile("docx");
var Document = Api.GetDocument();
var Paragraph = Document.GetElement(0);
var InlineLvlSdt = Api.CreateInlineLvlSdt();
var Run = Api.CreateRun();
Run.AddText("This is an inline text content control with the content lock set to it.");
InlineLvlSdt.AddElement(Run, 0);
InlineLvlSdt.SetLock("sdtContentLocked");
Paragraph.AddInlineLvlSdt(InlineLvlSdt);
var Lock = InlineLvlSdt.GetLock();
Paragraph = Api.CreateParagraph();
Paragraph.AddText("Lock type: " + Lock);
Document.Push(Paragraph);
builder.SaveFile("docx", "GetLock.docx");
builder.CloseFile();