builder.CreateFile("docx");
oDocument = Api.GetDocument();
oTableStyle = oDocument.CreateStyle("CustomTableStyle", "table");
oTableStyle.SetBasedOn(oDocument.GetStyle("Bordered - Accent 5"));
oTable = Api.CreateTable(3, 3);
oTable.SetWidth("percent", 100);
oTable.SetStyle(oTableStyle);
oDocument.Push(oTable);
oInlineLvlSdt = Api.CreateInlineLvlSdt();
oInlineLvlSdt.AddText("This is an inline text content control.");
oParagraph = Api.CreateParagraph();
oParagraph.AddElement(oInlineLvlSdt, 0);
oCell = oTable.GetRow(0).GetCell(0);
oCell.AddElement(0, oParagraph);
oParentTableCell = oInlineLvlSdt.GetParentTableCell();
oParentTableCell.SetShd("clear", 0xff, 0x68, 0x00, false);
builder.SaveFile("docx", "GetParentTableCell.docx");
builder.CloseFile();