builder.CreateFile("xlsx");
oWorksheet = Api.GetActiveSheet();
oPresetColor = Api.CreatePresetColor("lightYellow");
oGs1 = Api.CreateGradientStop(oPresetColor, 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 164, 101), 100000);
oFill = Api.CreateLinearGradientFill([oGs1, oGs2], 5400000);
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oWorksheet.AddShape("flowChartOnlineStorage", 60 * 36000, 35 * 36000, oFill, oStroke, 0, 2 * 36000, 1, 3 * 36000);
oClassType = oPresetColor.GetClassType();
oWorksheet.GetRange("A1").SetValue("Class Type: " + oClassType);
builder.SaveFile("xlsx", "GetClassType.xlsx");
builder.CloseFile();