builder.CreateFile("docx");
oDocument = Api.GetDocument();
oParagraph = oDocument.GetElement(0);
oRun = Api.CreateRun();
oRun.AddText("Api ONLYOFFICE DocBuilder");
oParagraph.AddElement(oRun);
oHyperlink = oParagraph.AddHyperlink("https://api.onlyoffice.com/");
oHyperlink.SetLink("http://api.teamlab.info/docbuilder/basic");
oHyperlink.SetScreenTipText("ONLYOFFICE for developers");
oHyperlink.SetDisplayedText("ONLYOFFICE Document Builder");
oLinkedText = oHyperlink.GetLinkedText();
oScreenTipText = oHyperlink.GetScreenTipText();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Linked text: " + oLinkedText);
oParagraph.AddLineBreak();
oParagraph.AddText("Screen tip text: " + oScreenTipText);
oDocument.Push(oParagraph);
oRange = oHyperlink.GetRange(0, 9);
oRange.SetBold(true);
builder.SaveFile("docx", "ApiHyperlink .docx");
builder.CloseFile();