builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oMaster = oPresentation.GetMaster(0);
sType = oMaster.GetClassType();
nCountBefore = oMaster.GetLayoutsCount();
oLayout = Api.CreateLayout();
oMaster.AddLayout(0, oLayout);
nCountAfterAdding = oMaster.GetLayoutsCount();
oMaster.RemoveLayout(0, 2);
nCountAfterRemoving = oMaster.GetLayoutsCount();
oFill = Api.CreateSolidFill(Api.CreateRGBColor(61, 74, 107));
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oShape = Api.CreateShape("flowChartMagneticTape", 300 * 36000, 130 * 36000, oFill, oStroke);
oShape.SetPosition(608400, 1267200);
oShape.SetSize(300 * 36000, 130 * 36000);
oDocContent = oShape.GetDocContent();
oParagraph = oDocContent.GetElement(0);
oParagraph.SetJc("left");
oParagraph.AddText("Number of layouts before adding new layout: " + nCountBefore);
oParagraph.AddLineBreak();
oParagraph.AddText("Number of layouts after adding new layout: " + nCountAfterAdding);
oParagraph.AddLineBreak();
oParagraph.AddText("Number of layouts after removing two layouts: " + nCountAfterRemoving);
oParagraph.AddLineBreak();
oParagraph.AddText("Class type = " + sType);
oSlide.RemoveAllObjects();
oMaster.AddObject(oShape);
oSlide = Api.CreateSlide();
oPresentation.AddSlide(oSlide);
oMaster = oPresentation.GetMaster(0);
nCountBefore = oPresentation.GetMastersCount();
oMaster.Duplicate(1);
nCountAfter = oPresentation.GetMastersCount();
oFill = Api.CreateSolidFill(Api.CreateRGBColor(61, 74, 107));
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oShape = Api.CreateShape("flowChartMagneticTape", 300 * 36000, 130 * 36000, oFill, oStroke);
oShape.SetPosition(608400, 1267200);
oShape.SetSize(300 * 36000, 130 * 36000);
oDocContent = oShape.GetDocContent();
oParagraph = oDocContent.GetElement(0);
oParagraph.SetJc("left");
oParagraph.AddText("Number of masters before duplicating: " + nCountBefore);
oParagraph.AddLineBreak();
oParagraph.AddText("Number of masters after duplicating: " + nCountAfter);
oSlide.RemoveAllObjects();
oSlide.AddObject(oShape);
builder.SaveFile("pptx", "ApiMaster.pptx");
builder.CloseFile();