builder.CreateFile("pptx");
var oPresentation = Api.GetPresentation();
var oSlide = oPresentation.GetSlideByIndex(0);
var oMaster = oPresentation.GetMaster();
var oFill = Api.CreateSolidFill(Api.CreateRGBColor(104, 155, 104));
oMaster.SetBackground(oFill);
var oDuplicateMaster = oMaster.Duplicate(1);
oDuplicateMaster.ClearBackground();
builder.SaveFile("pptx", "ClearBackground.pptx");
builder.CloseFile();