builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oMaster = Api.CreateMaster();
oPresentation.AddMaster(oMaster);
oLayout1 = Api.CreateLayout(oMaster);
oLayout2 = Api.CreateLayout(oMaster);
oMaster.RemoveLayout(0, 1);
oSlide.RemoveAllObjects();
oFill = Api.CreateSolidFill(Api.CreateRGBColor(61, 74, 107));
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oShape = Api.CreateShape("flowChartMagneticTape", 300 * 36000, 130 * 36000, oFill, oStroke);
oShape.SetPosition(608400, 1267200);
oShape.SetSize(300 * 36000, 130 * 36000);
oDocContent = oShape.GetDocContent();
oParagraph = oDocContent.GetElement(0);
oParagraph.SetJc("left");
oParagraph.AddText("The first layout was deleted from the slide master.");
oSlide.AddObject(oShape);
builder.SaveFile("pptx", "RemoveLayout.pptx");
builder.CloseFile();