builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 218, 185), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(238, 203, 173), 100000);
oFill1 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oBgFill1 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oStroke1 = Api.CreateStroke(0, oFill1);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(238, 149, 114), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 114, 86), 100000);
oFill2 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oBgFill2 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oStroke2 = Api.CreateStroke(0, oFill2);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 127, 36), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(238, 118, 33), 100000);
oFill3 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oBgFill3 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oStroke3 = Api.CreateStroke(0, oFill3);
oFormatScheme = Api.CreateThemeFormatScheme([oFill1, oFill2, oFill3], [oBgFill1, oBgFill2, oBgFill3], [oStroke1, oStroke2, oStroke3], "New format scheme");
oTheme = oSlide.GetTheme();
oTheme.SetFormatScheme(oFormatScheme);
builder.SaveFile("pptx", "SetFormatScheme.pptx");
builder.CloseFile();