builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oPictureForm = Api.CreatePictureForm({"key": "Personal information", "tip": "Upload your photo", "required": true, "placeholder": "Photo", "scaleFlag": "tooBig", "lockAspectRatio": true, "respectBorders": false, "shiftX": 50, "shiftY": 50});
var oParagraph = oDocument.GetElement(0);
oParagraph.AddElement(oPictureForm);
var oCopyPictureForm = oPictureForm.Copy();
oParagraph.AddLineBreak();
oParagraph.AddElement(oCopyPictureForm);
builder.SaveFile("docx", "Copy.docx");
builder.CloseFile();