builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oPictureForm = Api.CreatePictureForm({"key": "Personal information", "tip": "Upload your photo", "required": true, "placeholder": "Photo", "scaleFlag": "tooBig", "lockAspectRatio": true, "respectBorders": false, "shiftX": 50, "shiftY": 50});
var oParagraph = oDocument.GetElement(0);
oParagraph.AddElement(oPictureForm);
oPictureForm.SetImage("https://api.onlyoffice.com/content/img/editor/e-download.png");
var sImage = oPictureForm.GetImage();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("An image from the picture form in the base64 format: " + sImage);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "GetImage.docx");
builder.CloseFile();