builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var oRun = Api.CreateRun();
oRun.AddText("Add a picture form to the next line (Forms -> Image), copy the macro above (without the first and last two lines) and run it (Plugins -> Macros).");
oParagraph.AddElement(oRun);
var aPictureForm = oDocument.GetAllForms();
oParagraph.RemoveElement(0);
aPictureForm[0].SetImage("https://api.onlyoffice.com/content/img/editor/e-download.png");
var sScaleCase = aPictureForm[0].GetPictureScaleCase();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Picture scale case: " + sScaleCase);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "GetPictureScaleCase.docx");
builder.CloseFile();