builder.CreateFile("pptx");
var oPresentation = Api.GetPresentation();
var oTable = Api.CreateTable(3, 4);
var oRow = oTable.GetRow(0);
var oCell = oRow.GetCell(0);
oTable.RemoveColumn(oCell);
var oRow = oTable.GetRow(3);
var oCell = oRow.GetCell(0);
oTable.RemoveRow(oCell);
var oRow = oTable.GetRow(0);
var oCell1 = oRow.GetCell(0);
var oCell2 = oRow.GetCell(1);
oTable.MergeCells([oCell1, oCell2]);
var oCell = oRow.GetCell(0);
var oContent = oCell.GetContent();
var oParagraph = Api.CreateParagraph();
oParagraph.AddText("The first column was removed. The fourth row was removed. And the cells of the first row were merged.");
oContent.Push(oParagraph);
var oFill = Api.CreateSolidFill(Api.CreateRGBColor(520, 64, 1));
oTable.SetShd(oFill);
var oSlide = oPresentation.GetSlideByIndex(0);
oSlide.RemoveAllObjects();
oSlide.AddObject(oTable);
builder.SaveFile("pptx", "ApiTable.pptx");
builder.CloseFile();