builder.CreateFile("pptx");
var Presentation = Api.GetPresentation();
var Table = Api.CreateTable(2, 4);
var Row = Table.GetRow(0);
var Cell1 = Row.GetCell(0);
var Cell2 = Row.GetCell(1);
Table.MergeCells([Cell1, Cell2]);
var Cell = Row.GetCell(0);
var Content = Cell.GetContent();
var Paragraph = Api.CreateParagraph();
Paragraph.AddText("This cell was formed by merging two cells.");
Content.Push(Paragraph);
var Slide = Presentation.GetSlideByIndex(0);
Slide.RemoveAllObjects();
Slide.AddObject(Table);
builder.SaveFile("pptx", "MergeCells.pptx");
builder.CloseFile();