builder.CreateFile("pptx");
var oPresentation = Api.GetPresentation();
var oSlide = oPresentation.GetSlideByIndex(0);
oSlide.RemoveAllObjects();
var oTable = Api.CreateTable(2, 4);
var oRow = oTable.GetRow(0);
var oCell = oRow.GetCell(0);
var oContent = oCell.GetContent();
var oParagraph = Api.CreateParagraph();
var sJSON = oTable.ToJSON();
var oRun = Api.CreateRun();
oRun.SetBold(true);
oRun.AddText("The ApiTable object in the JSON format: ");
oParagraph.AddElement(oRun);
oParagraph.AddText(sJSON.substring(0, 747) + "..");
oContent.Push(oParagraph);
oSlide.AddObject(oTable);
builder.SaveFile("pptx", "ToJSON.pptx");
builder.CloseFile();