builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 224, 204), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 164, 101), 100000);
oFill1 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oBgFill1 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oStroke1 = Api.CreateStroke(0, oFill1);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 224, 204), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 164, 0), 100000);
oFill2 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oBgFill2 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oStroke2 = Api.CreateStroke(0, oFill2);
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 224, 204), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(0, 164, 101), 100000);
oFill3 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oBgFill3 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oStroke3 = Api.CreateStroke(0, oFill3);
oFormatScheme = Api.CreateThemeFormatScheme([oFill1, oFill2, oFill3], [oBgFill1, oBgFill2, oBgFill3], [oStroke1, oStroke2, oStroke3], "New format scheme");
oTheme = oSlide.GetTheme();
oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(100, 214, 204), 0);
oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 164, 101), 100000);
oNewBgFill3 = Api.CreateRadialGradientFill([oGs1, oGs2]);
oFormatScheme.ChangeBgFillStyles([oNewBgFill1, oNewBgFill2, oNewBgFill3]);
oTheme.SetFormatScheme(oFormatScheme);
builder.SaveFile("pptx", "ChangeBgFillStyles.pptx");
builder.CloseFile();