builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide = oPresentation.GetSlideByIndex(0);
oSlide.RemoveAllObjects();
oMaster = oPresentation.GetMaster(0);
oTheme = oMaster.GetTheme();
oFormatScheme = oTheme.GetFormatScheme();
oFormatScheme.SetSchemeName("New format scheme name");
oFill = Api.CreateSolidFill(Api.CreateRGBColor(61, 74, 107));
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oShape = Api.CreateShape("flowChartMagneticTape", 300 * 36000, 130 * 36000, oFill, oStroke);
oShape.SetPosition(608400, 1267200);
oShape.SetSize(300 * 36000, 130 * 36000);
oDocContent = oShape.GetDocContent();
oParagraph = oDocContent.GetElement(0);
oParagraph.SetJc("left");
oParagraph.AddText("New name was set to the theme format scheme.");
oSlide.AddObject(oShape);
builder.SaveFile("pptx", "SetSchemeName.pptx");
builder.CloseFile();