builder.CreateFile("xlsx");
oWorksheet = Api.GetActiveSheet();
oWorksheet.GetRange("A1").SetValue("1");
oRange = oWorksheet.GetRange("A1");
oRange.AddComment("This is just a number.");
oComment = oRange.GetComment();
oComment.Delete();
oWorksheet.GetRange("A3").SetValue("The comment from the cell A1 was deleted.");
builder.SaveFile("xlsx", "Delete.xlsx");
builder.CloseFile();