builder.CreateFile("xlsx");
var Worksheet = Api.GetActiveSheet();
Worksheet.GetRange("A1").SetValue("1");
var Range = Worksheet.GetRange("A1");
Range.AddComment("This is just a number.");
var Comment = Range.GetComment();
var Text = Comment.GetText();
Worksheet.GetRange("A3").SetValue("Comment: ");
Worksheet.GetRange("B3").SetValue(Text);
builder.SaveFile("xlsx", "GetText.xlsx");
builder.CloseFile();