builder.CreateFile("docx");
var Document = Api.GetDocument();
var Paragraph = Document.GetElement(0);
var InlineLvlSdt = Api.CreateInlineLvlSdt();
var Run = Api.CreateRun();
Run.AddText("This is an inline text content contro.");
InlineLvlSdt.AddElement(Run, 0);
Paragraph.AddInlineLvlSdt(InlineLvlSdt);
builder.SaveFile("docx", "AddInlineLvlSdt.docx");
builder.CloseFile();