builder.CreateFile("xlsx");
oWorksheet = Api.GetActiveSheet();
oWorksheet.SetName("sheet 1");
oWorksheet.GetRange("A1").SetValue(51);
oWorksheet.GetRange("B1").SetValue(5);
oWorksheet.GetRange("C1").SetValue(3);
oWorksheet.GetRange("A2").SetValue(2);
oWorksheet.GetRange("A3").SetValue(8);
oWorksheet.GetRange("A4").SetValue(11);
oWorksheet.GetRange("A5").SetValue(1);
oWorksheet.GetRange("B2").SetValue(48);
oWorksheet.GetRange("B3").SetValue(20);
oWorksheet.GetRange("B4").SetValue(31);
oWorksheet.GetRange("B5").SetValue(47);
oWorksheet.GetRange("C2").SetValue(21);
oWorksheet.GetRange("C3").SetValue(41);
oWorksheet.GetRange("C4").SetValue(18);
oWorksheet.GetRange("C5").SetValue(20);
oRange = oWorksheet.GetRange("A1:C5");
oRange.SetSort("A1:A5", "xlAscending", "B1:B5", "xlDescending", "C1:C5", "xlAscending", "xlNo", "xlSortColumns");
builder.SaveFile("xlsx", "SetSort.xlsx");
builder.CloseFile();