builder.CreateFile("xlsx");
var oWorksheet = Api.GetActiveSheet();
oWorksheet.GetRange("A1").SetValue("1");
var oRange = oWorksheet.GetRange("A1");
oRange.AddComment("This is just a number.");
var oComments = oWorksheet.GetComments();
oWorksheet.GetRange("A3").SetValue("Comments: ");
oWorksheet.GetRange("B3").SetValue(oComments);
oWorksheet.GetRange("A4").SetValue("We got all the comments on the worksheet in variable 'Comments'.");
builder.SaveFile("xlsx", "GetComments.xlsx");
builder.CloseFile();