builder.CreateFile("xlsx");
var Worksheet = Api.GetActiveSheet();
Worksheet.GetRange("A1").SetValue("1");
Worksheet.GetRange("B1").SetValue("2");
Worksheet.GetRange("A2").SetValue("A");
Worksheet.GetRange("B2").SetValue("B");
Worksheet.AddDefName("numbers", "Sheet1!$A$1:$B$1");
Worksheet.AddDefName("letters", "Sheet1!$A$2:$B$2");
var DefNames = Worksheet.GetDefNames();
Worksheet.GetRange("A4").SetValue("We got the objects of all the names on the  worksheet in variable 'DefNames'.");
builder.SaveFile("xlsx", "GetDefNames.xlsx");
builder.CloseFile();