builder.CreateFile("xlsx");
var Worksheet = Api.GetActiveSheet();
Worksheet.GetRange("A1").SetValue("1");
Worksheet.GetRange("B1").SetValue("2");
Worksheet.GetRange("C1").SetValue("3");
var Count = Worksheet.GetRange("A1:C1").GetCount();
Worksheet.GetRange("A4").SetValue("Count: ");
Worksheet.GetRange("B4").SetValue(Count);
builder.SaveFile("xlsx", "GetCount.xlsx");
builder.CloseFile();