builder.CreateFile("docx");
oDocument = Api.GetDocument();
oTableStyle = oDocument.CreateStyle("CustomTableStyle", "table");
oTableStyle.SetBasedOn(oDocument.GetStyle("Bordered - Accent 5"));
oTable = Api.CreateTable(3, 3);
oTable.SetWidth("percent", 100);
oTable.SetStyle(oTableStyle);
oDocument.Push(oTable);
oRun = Api.CreateRun();
oRun.AddText("This is just a sample text.");
oCell = oTable.GetRow(0).GetCell(0);
oCell.AddElement(oRun);
oParentTableCell = oRun.GetParentTableCell();
oParentTableCell.SetCellBorderTop("single", 32, 0, 0, 0, 255);
builder.SaveFile("docx", "GetParentTableCell.docx");
builder.CloseFile();