builder.CreateFile("pptx");
oPresentation = Api.GetPresentation();
oSlide1 = oPresentation.GetSlideByIndex(0);
oSlide2 = Api.CreateSlide();
oPresentation.AddSlide(oSlide2);
nSlides = oPresentation.GetSlidesCount();
oSlide1.RemoveAllObjects();
oFill = Api.CreateSolidFill(Api.CreateRGBColor(61, 74, 107));
oStroke = Api.CreateStroke(0, Api.CreateNoFill());
oShape = Api.CreateShape("flowChartMagneticTape", 300 * 36000, 130 * 36000, oFill, oStroke);
oShape.SetPosition(608400, 1267200);
oShape.SetSize(300 * 36000, 130 * 36000);
oDocContent = oShape.GetDocContent();
oParagraph = oDocContent.GetElement(0);
oParagraph.SetJc("left");
oParagraph.AddText("Number of slides = " + nSlides);
oSlide1.AddObject(oShape);
builder.SaveFile("pptx", "GetSlidesCount.pptx");
builder.CloseFile();