builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var oGs1 = Api.CreateGradientStop(Api.CreateRGBColor(255, 224, 204), 0);
var oGs2 = Api.CreateGradientStop(Api.CreateRGBColor(255, 164, 101), 100000);
var oFill = Api.CreateLinearGradientFill([oGs1, oGs2], 5400000);
var oStroke = Api.CreateStroke(0, Api.CreateNoFill());
var oDrawing = Api.CreateShape("rect", 5930900, 395605, oFill, oStroke);
oParagraph.AddDrawing(oDrawing);
var nWidth = oDrawing.GetWidth();
var oDocContent = oDrawing.GetContent();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Drawing width: " + nWidth / 36000 + " mm");
oDocContent.AddElement(0, oParagraph);
builder.SaveFile("docx", "GetWidth.docx");
builder.CloseFile();