builder.CreateFile("docx");
oDocument = Api.GetDocument();
oBlockLvlSdt = Api.CreateBlockLvlSdt();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("This is the first paragraph of the content control.");
oBlockLvlSdt.AddElement(oParagraph, 0);
oContent = oBlockLvlSdt.GetContent();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("This is the second paragraph of the content control.");
oContent.AddElement(oParagraph);
oContent.Push(oParagraph);
oDocument.AddElement(0, oBlockLvlSdt);
aParagraphs = oBlockLvlSdt.GetAllParagraphs();
aParagraphs[0].SetBold(true);
oBlockLvlSdt.Search("paragraph")[1].SetItalic(true);
oBlockLvlSdt.SetLabel("2147483647");
oBlockLvlSdt.SetLock("sdtContentLocked");
oBlockLvlSdt.SetAlias("№1");
oBlockLvlSdt.SetTag("This is a tag.");
oLabel = oBlockLvlSdt.GetLabel();
oLock = oBlockLvlSdt.GetLock();
oAlias = oBlockLvlSdt.GetAlias();
oTag = oBlockLvlSdt.GetTag();
oClassType = oBlockLvlSdt.GetClassType();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Class type: " + oClassType);
oParagraph.AddLineBreak();
oParagraph.AddText("Lock type: " + oLock);
oParagraph.AddLineBreak();
oParagraph.AddText("Label: " + oLabel);
oParagraph.AddLineBreak();
oParagraph.AddText("Alias: " + oAlias);
oParagraph.AddLineBreak();
oParagraph.AddText("Tag: " + oTag);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "ApiBlockLvlSdt.docx");
builder.CloseFile();