builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oBlockLvlSdt = Api.CreateBlockLvlSdt();
var oParagraph = Api.CreateParagraph();
oParagraph.AddText("This is a block text content control with the content lock set to it.");
oBlockLvlSdt.AddElement(oParagraph, 0);
oBlockLvlSdt.SetLock("sdtContentLocked");
oDocument.AddElement(0, oBlockLvlSdt);
builder.SaveFile("docx", "SetLock.docx");
builder.CloseFile();