builder.CreateFile("docx");
oDocument = Api.GetDocument();
oBlockLvlSdt = Api.CreateBlockLvlSdt();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("This is a block text content control with a label set to it.");
oBlockLvlSdt.AddElement(oParagraph, 0);
oBlockLvlSdt.SetLabel("2147483647");
oDocument.AddElement(0, oBlockLvlSdt);
oLabel = oBlockLvlSdt.GetLabel();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Label: " + oLabel);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "SetLabel.docx");
builder.CloseFile();