builder.CreateFile("docx");
oDocument = Api.GetDocument();
oBlockLvlSdt = Api.CreateBlockLvlSdt();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("This is a block text content control with a tag set to it.");
oBlockLvlSdt.AddElement(oParagraph, 0);
oBlockLvlSdt.SetTag("This is a tag.");
oDocument.AddElement(0, oBlockLvlSdt);
oTag = oBlockLvlSdt.GetTag();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Tag: " + oTag);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "SetTag.docx");
builder.CloseFile();