builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
var oNumbering = Api.CreateNumbering('ArabicPeriod', 1);
oParagraph.SetNumbering(oNumbering);
oParagraph.AddText("This is an example of the numbered paragraph.");
oParagraph = Api.CreateParagraph();
oParagraph.SetNumbering(oNumbering);
oParagraph.AddText("This is an example of the numbered paragraph.");
oDocument.Push(oParagraph);
builder.SaveFile("docx", "CreateNumbering.docx");
builder.CloseFile();
