builder.CreateFile("docx");
var Document = Api.GetDocument();
var Paragraph = Document.GetElement(0);
var Numbering = Api.CreateNumbering('ArabicPeriod', 1);
Paragraph.SetNumbering(Numbering);
Paragraph.AddText("This is an example of the numbered paragraph.");
Paragraph = Api.CreateParagraph();
Paragraph.SetNumbering(Numbering);
Paragraph.AddText("This is an example of the numbered paragraph.");
Document.Push(Paragraph);
builder.SaveFile("docx", "CreateNumbering.docx");
builder.CloseFile();
