builder.CreateFile("xlsx");
oWorksheet = Api.GetActiveSheet();
oWorksheet.GetRange("B4").SetValue("1");
oWorksheet.GetRange("C4").SetValue("2");
oWorksheet.GetRange("D4").SetValue("3");
oRangeFrom = oWorksheet.GetRange("B4:D4");
oRange = oWorksheet.GetRange("A1:C1");
oRange.Paste(oRangeFrom);
builder.SaveFile("xlsx", "Paste.xlsx");
builder.CloseFile();